### PR TITLE
MBUILD-145 Strike and Dodge UI

### PR DESCRIPTION
**Pull request by jfduedu**
As part of the plan to make the game more fun for users, I have implemented a Strike and Dodge UI. 
It consists of two functions: hitScreen and dodgeScreen. Both have different methods of input so I also added a tutorial.

Please see the issue for testing information.

### CODE REVIEW

**Review by NickPerillo4 — COMMENTED** [review]
Looks good works as intended. Maybe for the boss and the dragon we can make it so theres only one arrow key that you can click to dodge. And for the hit for the dragon and boss there can be smaller green box that does two hits but its really hard to hit. Just a thought

**Comment by jfduedu** [comment]
> Maybe for the boss and the dragon we can make it so theres only one arrow key that you can click to dodge. And for the hit for the dragon and boss there can be smaller green box that does two hits but its really hard to hit. Just a thought

Makes sense! HitScreen can be changed by speed, as well as the hit box (by using the string). DodgeScreen doesn't have that yet, but can do. To have custom hit attributes, MBUILD-148 would need to be adjusted after this merges.

**Comment by NickPerillo4** [comment]
The dodge screen just skips passed the tutorial and there's no time to read it

**Comment by jfduedu** [comment]
> The dodge screen just skips passed the tutorial and there's no time to read it

I couldn't replicate it, but I think it might be because of multiple inputs.
If the newest commit doesn't solve it, please copy everything in the terminal and paste it here.

**Review by NickPerillo4 — APPROVED** [review]
Works as intended now

**Comment by jfduedu** [comment]
Great! Will merge.

**Pull request merged**
